spring.application.name=async-scale
spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT:4001}

allowed.origins=${FRONTEND_URL:http://localhost:5173}

rate.limit.window.size.millis=${RATE_LIMIT_WINDOW_SIZE_MILLIS:60000}
rate.limit.max.usage=${MAX_RATE_LIMIT_USAGE:10}
rate.limit.cleanup.interval.millis=${RATE_LIMIT_CLEANUP_INTERVAL_MILLIS:60000}

websocket.max.active.socket=${WEBSOCKET_MAX_ACTIVE_SOCKET:10}

simulation.max.concurrent.instance=${SIMULATION_MAX_CONCURRENT_INSTANCE:3}

# postgres properties
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}

# spring.datasource.driver-class-name=${DB_DRIVER}
# spring.jpa.database-platform=${DB_PLATFORM}

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# spring.sql.init.mode=always
# spring.jpa.defer-datasource-initialization=true
